# Generated by Django 3.2.6 on 2021-09-19 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_vote_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 11, 48, 13, 895310, tzinfo=utc), verbose_name='date expired'),
            preserve_default=False,
        ),
    ]
